<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicolás Del Gobbo, Simón Rubinstein, Nicole Fabre, Gonzalo Coccolo, Martina Cortez">

<title>Estudio de alta frecuencia de la riqueza del plancton microbiano en el Atlántico Sudoccidental Sur</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Tp_entregar_files/libs/clipboard/clipboard.min.js"></script>
<script src="Tp_entregar_files/libs/quarto-html/quarto.js"></script>
<script src="Tp_entregar_files/libs/quarto-html/popper.min.js"></script>
<script src="Tp_entregar_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Tp_entregar_files/libs/quarto-html/anchor.min.js"></script>
<link href="Tp_entregar_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Tp_entregar_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Tp_entregar_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Tp_entregar_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Tp_entregar_files/libs/bootstrap/bootstrap-6afc3b510a42d3bba38ba6c6c601127c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estudio de alta frecuencia de la riqueza del plancton microbiano en el Atlántico Sudoccidental Sur</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nicolás Del Gobbo, Simón Rubinstein, Nicole Fabre, Gonzalo Coccolo, Martina Cortez </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<style type="text/css">
.justify {
  text-align: justify !important
}

.figure figcaption {
            text-align: center;
}
</style>
</div>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="introducción" class="level1">
<h1>Introducción</h1>
<div class="justify">
<p>Las aguas oceánicas de la capa eufótica están pobladas por microorganismos planctónicos que sostienen las redes tróficas marinas y modulan ciclos biogeoquímicos globales (Falkowski et al., 2008). Sus comunidades son transportadas pasivamente por las corrientes, cuyas condiciones físico-químicas pueden alterar las abundancias celulares de los microorganismos. Comprender cómo varían estas comunidades a lo largo de gradientes ambientales es una pregunta central en ecología microbiana marina y, a su vez, representa un desafío particular ya que la naturaleza dinámica del fluido marino no permite distinguir fácilmente los efectos relativos de las dimensiones espacial y temporal.</p>
<p>A escala planetaria, estas comunidades unicelulares están influenciadas por diferencias de temperatura y radiación solar a lo largo del gradiente latitudinal, así como por grandes patrones de mezcla, estratificación y disponibilidad de nutrientes, los cuales dependen de la ubicación relativa a los continentes, los giros oceánicos subtropicales y las principales corrientes marinas, cada uno con sus propias variaciones estacionales e interanuales. En la mesoescala, los frentes marinos y los remolinos de entre 10-100 km de extensión modifican las condiciones del medio marino por períodos de semanas a meses, mientras que procesos vinculados a estructuras menores de una magnitud de 1-10 km (aquellas denominadas de sub-mesoescala) pueden influir como forzantes ecológicos por lapsos de horas a días. Las tasas de renovación de biomasa y de composición comunitaria integran señales provenientes de todas estas escalas (Levy et al., 2015).</p>
<p>Dentro de este marco, el sector sudoccidental del Atlántico Sur (SOAS) representa un sistema ideal para estudiar cómo distintos forzantes estructuran comunidades planctónicas a lo largo de sus marcados gradientes ambientales. Al sur del 40°S, y adyacente al continente sudamericano, se sitúa la Plataforma Patagónica, una región de alta productividad primaria y biodiversidad (Rivas et al., 2006). Desde el sur ingresan aguas subantárticas de baja salinidad, influenciadas por el aporte de masas de agua procedentes del Estrecho de Magallanes, originadas en las zonas de alta precipitación al oeste de la cordillera (Piola et al., 2018). La plataforma presenta una batimetría amplia y relativamente plana, que se interrumpe bruscamente hacia los 200 m de profundidad, dando paso a un talud que desciende hasta los 4000 m. A lo largo del talud, en dirección N-NE, circula la Corriente de Malvinas, la cual es un desprendimiento de la Corriente Circumpolar Antártica. Esta corriente fría y rica en macronutrientes posee una salinidad relativamente mayor que las aguas de plataforma, generando un frente termohalino permanente pero de intensidad moderada.</p>
<p>El SOAS se caracteriza por una fuerte estacionalidad, con floraciones fitoplanctónicas extensas entre la primavera y el verano. De forma general, estas floraciones ocurren al norte de 45°S entre septiembre y noviembre, y al sur entre noviembre y enero (Romero et al., 2006). Durante este período productivo suele observarse una sucesión de grupos dominantes, incluyendo diatomeas, dinoflagelados y pequeños flagelados como los cocolitofóridos (Guinder et al., 2024). Sin embargo, imágenes satelitales y campañas recientes revelan un escenario más heterogéneo —especialmente en aguas de plataforma— con múltiples parches en mesoescala dominados por una o pocas especies (Ferronato et al., 2025). Para atribuir cambios comunitarios a diferencias espaciales en un entorno físicamente tan dinámico, es necesario contar con alta densidad o frecuencia de muestreo en el espacio y en el tiempo.</p>
</div>
<section id="objetivos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos">Objetivos</h2>
<div class="justify">
<p>Se propone estudiar los cambios en la riqueza de las comunidades de plancton microbiano a lo largo de los frentes del talud continental y de transición a una floración fitoplanctónica, a partir de la salinidad superficial y el tamaño de los organismos que componen a la comunidad. Se analizarán las variaciones en las comunidades, tanto en la mesoescala como en la submesoescala.</p>
</div>
<section id="hipótesis" class="level3">
<h3 class="anchored" data-anchor-id="hipótesis">Hipótesis</h3>
<div class="justify">
<p>La riqueza se ve afectada tanto por la salinidad como por las estructuras de las comunidades. De esta forma, las condiciones asociadas a los frentes de mesoescala presentan una menor riqueza con una dominancia de especies especialistas, mientras que, las que modelan de forma moderada a los frentes de submesoescala, están asociadas a una mayor riqueza.</p>
</div>
</section>
<section id="predicciones" class="level3">
<h3 class="anchored" data-anchor-id="predicciones">Predicciones</h3>
<div class="justify">
<p>Se espera encontrar una mayor riqueza asociada a aguas internas de la plataforma, las cuales presentan alteraciones moderadas en sus condiciones, con una salinidad relativamente baja y un mayor tamaño de organismos.</p>
<p>Además, se espera que la riqueza sea menor en aguas del talud, del lado este del frente, donde la salinidad es máxima y la comunidad está dominada, al momento del muestreo, por organismos pequeños como los cocolitofóridos y en menor parte los dinoflagelados desnudos.</p>
</div>
</section>
</section>
<section id="metodología" class="level2">
<h2 class="anchored" data-anchor-id="metodología">Metodología</h2>
<div class="justify">
<p>Para estudiar cómo varía la diversidad en los frentes oceánicos, se utilizaron datos provenientes de una campaña de muestreo de tres semanas realizada en diciembre de 2021 a bordo de la goleta científica Tara. El muestreo combinó mediciones continuas y semicontinuas obtenidas mediante el bombeo de agua superficial hacia instrumentos instalados a bordo, junto con estaciones discretas para recolectar muestras de agua y biomasa a distintas profundidades.</p>
<p>Se realizaron dos transectas, una atravesando el frente del talud continental (desde el talud, donde las aguas son más salobres y profundas) y otro sobre la plataforma, atravesando una floración fitoplanctónica de la plataforma continental.&nbsp;</p>
<p>Para evaluar la diversidad, se utilizó la riqueza en 5ml de agua como variable respuesta. Luego, las variables explicativas medidas en la expedición fueron la salinidad superficial (SSS[UPS]), el tamaño de partículas <span class="math inline">\(^{-1}\)</span> (gamma), temperatura superficial (SST[°C]), indice de refractancia de las particulas (bbp[mg/m3)], la clorofila (Chl[mg/m3]) y el carbono orgánico particulado (POC[mg/m3]). Además de si se trataba de transecta realizada sobre el frente estable del talud continental o si era el transitorio de aguas internas de la plataforma. Por otro lado, se calcularon las distancias entre cada punto de muestreo utilizando el paquete geosphere (RJ. Hijmans, 2024 ), con el fin de evaluar la independencia de las observaciones, a partir de las coordenadas geográficas del velero.</p>
<p>Los registros de temperatura y salinidad fueron obtenidos mediante un termosalinógrafo instalado a bordo, y las estimaciones de concentración de clorofila “a” fueron obtenidas por un fluorómetro.</p>
<p>Las mediciones semicontinuas consistieron en observaciones de grupos planctónicos a través de un sistema que combina microfluídica y microscopía, denominado Imaging FlowCytobot (IFCB). Este instrumento captura imágenes microscópicas de partículas presentes en 5 mL de agua de mar, aproximadamente cada 30 minutos, y está optimizado para detectar organismos con diámetros entre 5 y 20 micrones. Las imágenes obtenidas se analizan posteriormente mediante la plataforma EcoTaxa.</p>
<p>El análisis computacional fue realizado utilizando el entorno y lenguaje R (R Core Team, 2024). Además se utilizó un diverso número de paquetes como ggplot2 (H. Wickham, 2016) para realizar gráficos exploratorios. El análisis de los residuales de los modelos con una distribución de probabilidades de Poisson se efectuaron utilizando el paquete ‘DHARMa’ (F. Hartig, 2020).</p>
</div>
<section id="modelo-inicial" class="level4">
<h4 class="anchored" data-anchor-id="modelo-inicial">Modelo Inicial</h4>
<div class="justify">
<p>Debido a que la riqueza en 5ml es un conteo de taxones en un continuo, presentando una cota inferior pero no superior, se propone que sigue una distribución de probabilidades de tipo Poisson.</p>
<p>Como los datos se toman en una serie espacial, no se puede asumir independencia entre las muestras. Por ende abordaremos un modelo marginal con un diseño de medidas repetidas en el <strong>espacio</strong>, donde la falta de independencia de los datos con una matriz de covarianzas. Este es un modelo generalizado lineal, ya que la variable respuesta tiene una distribución Poisson y se usan medidas repetidas (GEE).</p>
</div>
<p><span class="math display">\[
\begin{gather}
\ln( E ( \frac {Riqueza}{5 ~ ml ~ Agua}))_i = \beta_0 + \beta_1 + SSS_ị \beta_2  TamañoParticulas_i + \beta_3 SST_i +  \beta_4 bbp_i  + \beta_5 Clorofila_i  + \beta_6 POC_i + \beta_7 Estable_i + \beta_8 Distancia_i
\\ (\frac  {Riqueza}{5 ~ ml ~ Agua})_i   \sim Poisson ( \lambda_i)
\end{gather}
\]</span></p>
<p>Como en GEE no existe una matriz de correlación continua de distancias, asumimos una autroregresiva de orden uno, debido a que las distancias entre los puntos se mantienen relativamente constantes.</p>
<hr>
</section>
</section>
<section id="desarollo-analisis" class="level2">
<h2 class="anchored" data-anchor-id="desarollo-analisis">Desarollo Analisis</h2>
<section id="transformación-datos" class="level3">
<h3 class="anchored" data-anchor-id="transformación-datos">Transformación datos</h3>
<p>Para comenzar, se pasaron las latitudes y longitudes a distancias, tomando un punto de cada fuente como referencia y renombramos los frentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>datos_crudos <span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"../datos/complete_data.csv"</span>, <span class="at">header=</span>T)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos_crudos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  object_id              lat              lon            source         
 Length:75          Min.   :-49.29   Min.   :-64.00   Length:75         
 Class :character   1st Qu.:-48.57   1st Qu.:-63.86   Class :character  
 Mode  :character   Median :-46.37   Median :-61.53   Mode  :character  
                    Mean   :-47.05   Mean   :-61.94                     
                    3rd Qu.:-46.03   3rd Qu.:-60.50                     
                    Max.   :-45.67   Max.   :-59.74                     
    riqueza           Chl               POC            gamma        
 Min.   :10.00   Min.   : 0.4548   Min.   :105.9   Min.   :0.01552  
 1st Qu.:14.00   1st Qu.: 0.6219   1st Qu.:136.0   1st Qu.:0.46007  
 Median :17.00   Median : 1.5955   Median :204.1   Median :0.89590  
 Mean   :17.39   Mean   : 3.7664   Mean   :248.8   Mean   :0.78349  
 3rd Qu.:19.00   3rd Qu.: 4.8241   3rd Qu.:339.3   3rd Qu.:1.03459  
 Max.   :32.00   Max.   :19.6760   Max.   :615.9   Max.   :1.43580  
      SST             SSS             bbp          
 Min.   :10.84   Min.   :33.23   Min.   :0.000643  
 1st Qu.:11.53   1st Qu.:33.40   1st Qu.:0.001404  
 Median :11.88   Median :33.50   Median :0.001794  
 Mean   :12.32   Mean   :33.49   Mean   :0.002673  
 3rd Qu.:13.35   3rd Qu.:33.56   3rd Qu.:0.002660  
 Max.   :13.59   Max.   :33.88   Max.   :0.010674  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">####DISTANCIA####</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Coordenadas iniciales por localidad</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ref_points <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">source =</span> <span class="fu">c</span>(<span class="st">"bloom"</span>, <span class="st">"talud"</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ref_lat =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">48.2656</span>, <span class="sc">-</span><span class="fl">45.6659</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ref_lon =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">63.7595</span>, <span class="sc">-</span><span class="fl">59.7381</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular distancia al punto inicial de cada localidad</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>datos_crudos <span class="ot">&lt;-</span> datos_crudos <span class="sc">%&gt;%</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(ref_points, <span class="at">by =</span> <span class="st">"source"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist_m =</span> <span class="fu">distHaversine</span>(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">p1 =</span> <span class="fu">cbind</span>(ref_lon, ref_lat),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">p2 =</span> <span class="fu">cbind</span>(lon, lat)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist =</span> dist_m <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> datos_crudos[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">12</span><span class="sc">:</span><span class="dv">14</span> )]</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>source <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(datos<span class="sc">$</span>source,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"bloom"</span> <span class="ot">=</span> <span class="st">"transitorio"</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"talud"</span> <span class="ot">=</span> <span class="st">"estable"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analisis-exploratorio-datos" class="level3">
<h3 class="anchored" data-anchor-id="analisis-exploratorio-datos">Analisis Exploratorio Datos</h3>
<section id="analiticamente" class="level4">
<h4 class="anchored" data-anchor-id="analiticamente">Analiticamente</h4>
<p>Se realiza un resumen de las variables explicativas por cada frente, observando las medias y la cantidad de muestras en cada una.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>resumen_frente <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(source) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">riqueza =</span> <span class="fu">mean</span>(riqueza),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">salinidad =</span> <span class="fu">mean</span>(SSS),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">chl =</span> <span class="fu">mean</span>(Chl),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">POC =</span> <span class="fu">mean</span>(POC),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">gamma =</span> <span class="fu">mean</span>(gamma),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">SST =</span> <span class="fu">mean</span>(SST),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">bbp =</span> <span class="fu">mean</span>(bbp)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>knitr <span class="sc">::</span> <span class="fu">kable</span>(resumen_frente,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>               </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>               <span class="at">caption =</span> <span class="st">"Medidas resumen por frente "</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Medidas resumen por frente</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">source</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">riqueza</th>
<th style="text-align: right;">salinidad</th>
<th style="text-align: right;">chl</th>
<th style="text-align: right;">POC</th>
<th style="text-align: right;">gamma</th>
<th style="text-align: right;">SST</th>
<th style="text-align: right;">bbp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">transitorio</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">21.80</td>
<td style="text-align: right;">33.33616</td>
<td style="text-align: right;">7.966973</td>
<td style="text-align: right;">363.3142</td>
<td style="text-align: right;">0.3174908</td>
<td style="text-align: right;">11.54059</td>
<td style="text-align: right;">0.0047610</td>
</tr>
<tr class="even">
<td style="text-align: left;">estable</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">15.18</td>
<td style="text-align: right;">33.56649</td>
<td style="text-align: right;">1.666169</td>
<td style="text-align: right;">191.6131</td>
<td style="text-align: right;">1.0164925</td>
<td style="text-align: right;">12.71537</td>
<td style="text-align: right;">0.0016287</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="graficamente" class="level4">
<h4 class="anchored" data-anchor-id="graficamente">Graficamente</h4>
<p>Se explora la relación entre las variables exploratorias con la variable respuesta, separando para cada frente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>linealidadPlot <span class="ot">=</span> <span class="cf">function</span> (var, nombre){</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x=</span>{{var}}, <span class="at">y=</span> riqueza,<span class="at">group =</span> source , <span class="at">color =</span> source)) <span class="sc">+</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(  <span class="at">size=</span><span class="dv">3</span>,  <span class="at">shape=</span><span class="dv">19</span> ) <span class="sc">+</span>  </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span>F, <span class="at">fullrange=</span>F, <span class="at">size=</span><span class="fl">0.5</span>)<span class="sc">+</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>( nombre ) <span class="sc">+</span>  <span class="fu">ylab</span>(<span class="st">"Riqueza"</span>) </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linealidadPlot</span>(Chl,<span class="st">"Clorofila [mg/m3]"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linealidadPlot</span>(POC,<span class="st">"POC [mg/m3]"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">linealidadPlot</span>(bbp,<span class="st">"bbp [mg/m3]"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">linealidadPlot</span>(gamma,<span class="st">"gamma"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">linealidadPlot</span>(SST,<span class="st">"Temperatura Superficial [°C]"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">linealidadPlot</span>(SSS,<span class="st">"Salinidad Superficial [UPS]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Tp_entregar_files/figure-html/explorativos-1.png" class="img-fluid" width="576"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Tp_entregar_files/figure-html/explorativos-2.png" class="img-fluid" width="576"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Tp_entregar_files/figure-html/explorativos-3.png" class="img-fluid" width="576"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Tp_entregar_files/figure-html/explorativos-4.png" class="img-fluid" width="576"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Tp_entregar_files/figure-html/explorativos-5.png" class="img-fluid" width="576"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Tp_entregar_files/figure-html/explorativos-6.png" class="img-fluid" width="576"></p>
</div>
</div>
</div>
</section>
<section id="correlacion" class="level4">
<h4 class="anchored" data-anchor-id="correlacion">Correlacion</h4>
<p>Como las variables medidas se esperan que estén correlacionadas, se realizó un gráfico de correlación para evaluar la misma, separando por cada frente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(datos[<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>], <span class="fu">aes</span> ( <span class="at">color =</span> source))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>m0<span class="ot">&lt;-</span><span class="fu">geeglm</span>(<span class="at">formula=</span> riqueza<span class="sc">~</span>Chl<span class="sc">+</span>SSS<span class="sc">+</span>source<span class="sc">+</span>gamma<span class="sc">+</span>bbp<span class="sc">+</span>POC<span class="sc">+</span>SST, <span class="at">family =</span> poisson, <span class="at">data=</span>datos,<span class="at">id=</span>source,<span class="at">corstr =</span> <span class="st">"ar1"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">vif</span>(m0), </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">3</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"VIF"</span>) <span class="co"># &lt;-- No format argument</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>VIF</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chl</td>
<td style="text-align: right;">1.184410e+14</td>
</tr>
<tr class="even">
<td style="text-align: left;">SSS</td>
<td style="text-align: right;">1.132750e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">source</td>
<td style="text-align: right;">1.135208e+15</td>
</tr>
<tr class="even">
<td style="text-align: left;">gamma</td>
<td style="text-align: right;">2.425235e+15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bbp</td>
<td style="text-align: right;">-6.744785e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">POC</td>
<td style="text-align: right;">1.005204e+14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SST</td>
<td style="text-align: right;">1.478070e+13</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A partir de esto se observa una alta correlación entre las variables explicativas, por lo que es necesario realizar una selección criteriosa de los modelos.</p>
</section>
<section id="modelo" class="level4">
<h4 class="anchored" data-anchor-id="modelo">Modelo</h4>
<p>Para comenzar se realiza un modelo con todas las variables explicativas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geepack)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(object_id)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>m0<span class="ot">&lt;-</span><span class="fu">geeglm</span>(<span class="at">formula=</span> riqueza<span class="sc">~</span>Chl<span class="sc">+</span>SSS<span class="sc">+</span>source<span class="sc">+</span>gamma<span class="sc">+</span>bbp<span class="sc">+</span>POC<span class="sc">+</span>SST, <span class="at">family =</span> poisson, <span class="at">data=</span>datos,<span class="at">id=</span>source,<span class="at">corstr =</span> <span class="st">"ar1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="supuestos" class="level3">
<h3 class="anchored" data-anchor-id="supuestos">Supuestos</h3>
<section id="dispersion" class="level4">
<h4 class="anchored" data-anchor-id="dispersion">Dispersion</h4>
<p>Se verifica la ausencia de sobre o subdispersión de los residuos de pearson.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">testDispersion</span>(m0, <span class="at">type =</span> <span class="st">"PearsonChisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Parametric dispersion test via mean Pearson-chisq statistic

data:  m0
dispersion = 0.58674, df = 67, p-value = 0.005528
alternative hypothesis: two.sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sim <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(<span class="at">fittedMod =</span> m0, <span class="at">plot =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="justify">
<p>Se observa subdipersion de los residuos, por lo que debe ser modelada con una distribución como Conway-Maxwell-Poisson para evitar sobrestimar los errores estándars.</p>
<p>Sin embargo, la librería GEE no presenta alternativas para la familia Poisson que corrijan la subdispersion ( la documentación dice la existencia de quasiPoisson pero no se logró que funcione) por lo que se descarta la posibilidad de modelar la subdispersión.</p>
<p>Ante este problema, se decide asumir que la distribución de probabilidades de la riqueza se asemeja a una distribución Normal debido a que la distribución Poisson con $\lambda$ mayor a ocho se aproxima a esta.</p>
</div>
</section>
</section>
<section id="plan-b" class="level3">
<h3 class="anchored" data-anchor-id="plan-b">Plan B</h3>
<section id="modelo-riqueza-normal" class="level4">
<h4 class="anchored" data-anchor-id="modelo-riqueza-normal">Modelo Riqueza ~ Normal</h4>
<p><span class="math display">\[
\begin{gather}
  Riqueza_i = \beta_0 + \beta_1 + SSS_ị \beta_2  TamañoParticulas_i + \beta_3 SST_i +  \beta_4 bbp_i  + \beta_5 Clorofila_i  + \beta_6 POC_i + \beta_7 Estable_i + \beta_8 Distancia_i + \epsilon_i
\\ \epsilon_i \sim Normal(0,\sigma^2_{frente})
\\ i : 1 -75
\end{gather}
\]</span></p>
<div class="justify">
<p>Como en Poisson mayor media equivale a mayor varianza, la homocedasticidad es problemática al convertirlo en Normal. Sin embaro, se encuentra que estimando una varianza para cada frente soluciona la falta de homocedasticidad. Se utilizó la función var Ident para el modelado de la varianza.</p>
<p>Asimismo se probaron var Power y var Exp pero los resultados no fueron satisfactorios debido a que no corrigen la heterocedasticidad. Además, el modelado de varianza por var Ident no presenta un aumento significativo de cantidad de parámetros estimados en comparación a los otros.</p>
</div>
</section>
</section>
</section>
</section>
<section id="ver-de-agregar-var-power-y-var-exp" class="level1">
<h1>VER de agregar var Power y var Exp</h1>
<section id="seleccion-de-modelos" class="level4">
<h4 class="anchored" data-anchor-id="seleccion-de-modelos">Seleccion de modelos</h4>
<div class="justify">
<p>Dada la alta correlación entre las variables explicativas, se decide por criterio de interés biológico seleccionar a la salinidad superficial y el Tamaño inverso de partículas. Como estas dos presentan una correlación entre ellas, no serán utilizados en el mismo modelo, sino que se generaran dos distintos: uno explicará las variaciones de la riqueza a partir del ambiente, mientras el otro lo hará a partir de las condiciones intrínsecas de la comunidad. Debido a la falta de linealidad de la salinidad se utiliza un polinomio de grado dos para este modelo.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>m_Nulo <span class="ot">=</span> <span class="fu">gls</span>(<span class="at">model =</span> riqueza <span class="sc">~</span> <span class="dv">1</span> , <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>source) , <span class="at">data =</span> datos,<span class="at">correlation =</span> <span class="fu">corCAR1</span>(<span class="at">form =</span> <span class="sc">~</span> dist<span class="sc">|</span>source))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>m_gamma<span class="ot">=</span><span class="fu">gls</span>(<span class="at">model =</span> riqueza <span class="sc">~</span> gamma   ,<span class="at">data =</span> datos, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>source),<span class="at">correlation =</span> <span class="fu">corCAR1</span>(<span class="at">form =</span> <span class="sc">~</span> dist<span class="sc">|</span>source))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>m_SSS2 <span class="ot">=</span> <span class="fu">gls</span>(<span class="at">model =</span> riqueza <span class="sc">~</span> <span class="fu">poly</span>(SSS, <span class="dv">2</span>)   ,<span class="at">data =</span> datos, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>source),<span class="at">correlation =</span> <span class="fu">corCAR1</span>(<span class="at">form =</span> <span class="sc">~</span> dist<span class="sc">|</span>source))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>m_SSS2ygamma <span class="ot">=</span> <span class="fu">gls</span>(<span class="at">model =</span> riqueza <span class="sc">~</span> <span class="fu">scale</span>(SSS) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">scale</span>(SSS)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> gamma, </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> datos, </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>source) ,<span class="at">correlation =</span> <span class="fu">corCAR1</span>(<span class="at">form =</span> <span class="sc">~</span> dist<span class="sc">|</span>source))</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>modelos <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nulo"</span> <span class="ot">=</span> m_Nulo,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Tamaño Particulas"</span> <span class="ot">=</span> m_gamma,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SSS^2"</span> <span class="ot">=</span> m_SSS2,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SSS^2 + Gamma"</span> <span class="ot">=</span> m_SSS2ygamma</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>aic_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(modelos, AIC)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>bic_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(modelos, BIC)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>rse_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(modelos, sigma)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>phi_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(modelos, <span class="cf">function</span>(m) {</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the correlation structure</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  cor_struct <span class="ot">&lt;-</span> <span class="fu">coef</span>(m<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, <span class="at">unconstrained =</span> <span class="cn">FALSE</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(cor_struct)){</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  cor_struct <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(cor_struct)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>p_value_last_coef <span class="ot">&lt;-</span> <span class="fu">sapply</span>(modelos, <span class="cf">function</span>(m) {</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the coefficient table from the summary</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  tTable <span class="ot">&lt;-</span> <span class="fu">summary</span>(m)<span class="sc">$</span>tTable</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the number of rows (which is the last coefficient)</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>  last_row <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tTable)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get the p-value from that last row</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>  p_val <span class="ot">&lt;-</span> tTable[last_row, <span class="st">"p-value"</span>]</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p_val)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">Phi =</span> phi_values,</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE =</span> rse_values,</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> aic_values,</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC =</span> bic_values,</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_valor =</span> p_value_last_coef</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(results_table, </span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">3</span>, </span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"GLS Model Comparison"</span>) <span class="co"># &lt;-- No format argument</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>GLS Model Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Phi</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">P_valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nulo.Phi</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7.597</td>
<td style="text-align: right;">422.611</td>
<td style="text-align: right;">431.827</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tamaño Particulas.Phi</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.662</td>
<td style="text-align: right;">401.200</td>
<td style="text-align: right;">412.652</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SSS^2.Phi</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.910</td>
<td style="text-align: right;">388.371</td>
<td style="text-align: right;">402.031</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SSS^2 + Gamma.Phi</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.727</td>
<td style="text-align: right;">392.939</td>
<td style="text-align: right;">408.778</td>
<td style="text-align: right;">0.055</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Se puede observar como al combinar ambos modelos el AIC disminuye, por ende se analizó la salinidad superficial y el gamma de forma independiente por un interés biológico.</p>
</section>
<section id="supuestos-1" class="level3">
<h3 class="anchored" data-anchor-id="supuestos-1">Supuestos</h3>
<p>No se encuentra evidencias suficientes para rechazar los supuestos de linealidad de las variables explicativas con la variable respuesta, la normalidad de los residuos, la homocedasticidad de las varianzas y la independencia de los datos con el gráfico ACF.</p>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>model_names <span class="ot">&lt;-</span> <span class="fu">names</span>(modelos)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (current_name <span class="cf">in</span> model_names) {</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> modelos[[current_name]]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">=</span> <span class="fu">residuals</span>(m , <span class="at">type =</span> <span class="st">"pearson"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  predichos <span class="ot">=</span> <span class="fu">predict</span>(m)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(predichos , r , <span class="at">main =</span> current_name)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">acf</span>(<span class="fu">resid</span>(m, <span class="at">type=</span><span class="st">"normalized"</span>), <span class="at">main=</span>current_name)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqPlot</span>(r)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">shapiro.test</span>(r))</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a> }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>
    Shapiro-Wilk normality test

data:  r
W = 0.9816, p-value = 0.3467</code></pre>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>
    Shapiro-Wilk normality test

data:  r
W = 0.97465, p-value = 0.137</code></pre>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>
    Shapiro-Wilk normality test

data:  r
W = 0.98244, p-value = 0.3852</code></pre>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>
    Shapiro-Wilk normality test

data:  r
W = 0.97955, p-value = 0.2658</code></pre>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de residuos de Pearson en función de los predichos.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-2.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Análisis de la función de autocorrelación (ACF) para el modelo nulo, y los modelos de riqueza tanto en función del tamaño de partículas inverso, como el cuadrático de salinidad superficial . Los tres modelos presentan la matriz de correlación explícita continua, autoregresiva de orden 1.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-3.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de cuantiles observados en función de los cuantiles teóricos.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-4.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de residuos de Pearson en función de los predichos.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-5.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Análisis de la función de autocorrelación (ACF) para el modelo nulo, y los modelos de riqueza tanto en función del tamaño de partículas inverso, como el cuadrático de salinidad superficial . Los tres modelos presentan la matriz de correlación explícita continua, autoregresiva de orden 1.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-6.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de cuantiles observados en función de los cuantiles teóricos.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-7.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de residuos de Pearson en función de los predichos.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-8.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Análisis de la función de autocorrelación (ACF) para el modelo nulo, y los modelos de riqueza tanto en función del tamaño de partículas inverso, como el cuadrático de salinidad superficial . Los tres modelos presentan la matriz de correlación explícita continua, autoregresiva de orden 1.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-9.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de cuantiles observados en función de los cuantiles teóricos.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-10.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de residuos de Pearson en función de los predichos.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-11.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Análisis de la función de autocorrelación (ACF) para el modelo nulo, y los modelos de riqueza tanto en función del tamaño de partículas inverso, como el cuadrático de salinidad superficial . Los tres modelos presentan la matriz de correlación explícita continua, autoregresiva de orden 1.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/alternativo-12.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Gráfico de cuantiles observados en función de los cuantiles teóricos.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<p>Diagnóstico del modelo</p>
</div>
</div>
</div>
</section>
<section id="resultados-finales" class="level2">
<h2 class="anchored" data-anchor-id="resultados-finales">Resultados Finales</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_SSS2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: riqueza ~ poly(SSS, 2) 
  Data: datos 
       AIC      BIC    logLik
  388.3711 402.0311 -188.1855

Correlation Structure: Continuous AR(1)
 Formula: ~dist | source 
 Parameter estimate(s):
         Phi 
9.636215e-15 
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | source 
 Parameter estimates:
transitorio     estable 
  1.0000000   0.5314462 

Coefficients:
                  Value Std.Error  t-value p-value
(Intercept)    17.17246  0.398542 43.08827       0
poly(SSS, 2)1 -18.22166  3.812801 -4.77907       0
poly(SSS, 2)2  21.09189  3.502766  6.02150       0

 Correlation: 
              (Intr) p(SSS,2)1
poly(SSS, 2)1 -0.463          
poly(SSS, 2)2  0.371 -0.463   

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.1168380 -0.5799157  0.0322753  0.5453694  2.7564371 

Residual standard error: 4.909523 
Degrees of freedom: 75 total; 72 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_gamma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: riqueza ~ gamma 
  Data: datos 
       AIC     BIC    logLik
  401.1997 412.652 -195.5998

Correlation Structure: Continuous AR(1)
 Formula: ~dist | source 
 Parameter estimate(s):
        Phi 
5.90014e-35 
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | source 
 Parameter estimates:
transitorio     estable 
  1.0000000   0.6160909 

Coefficients:
                Value Std.Error   t-value p-value
(Intercept) 22.352867  1.102099 20.282096       0
gamma       -6.748224  1.142268 -5.907741       0

 Correlation: 
      (Intr)
gamma -0.941

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-1.9746546 -0.6932941 -0.1069366  0.7764364  2.3063315 

Residual standard error: 4.662027 
Degrees of freedom: 75 total; 73 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m_SSS2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %    97.5 %
(Intercept)    16.39134  17.95359
poly(SSS, 2)1 -25.69461 -10.74871
poly(SSS, 2)2  14.22659  27.95718</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m_gamma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %   97.5 %
(Intercept) 20.192794 24.51294
gamma       -8.987029 -4.50942</code></pre>
</div>
</div>
<p>Para ambos modelos se encuentra que los estimadores son significativamente distintos de cero (p &lt; 0.05) y que poseen un Phi de covarianza muy bajo, cercano a cero. Sin embargo se decidió dejar la matriz de covarianzas ya que presentan mejor AIC que los mismos modelos sin considerarla.</p>
<section id="ecuación-estimada-de-la-riqueza-en-función-del-tamaño-de-partículas-inverso" class="level4">
<h4 class="anchored" data-anchor-id="ecuación-estimada-de-la-riqueza-en-función-del-tamaño-de-partículas-inverso">Ecuación estimada de la riqueza en función del tamaño de partículas inverso:</h4>
<p><span class="math display">\[
Riqueza = 22.353 - 6.748*TamPart
\]</span></p>
</section>
<section id="ecuación-estimada-de-la-riqueza-en-función-del-tamaño-de-la-salinidad-superficial" class="level4">
<h4 class="anchored" data-anchor-id="ecuación-estimada-de-la-riqueza-en-función-del-tamaño-de-la-salinidad-superficial">Ecuación estimada de la riqueza en función del tamaño de la salinidad superficial:</h4>
<p><span class="math display">\[
Riqueza = 17.17 - 18.22*SSS + 21.09*SSS²
\]</span></p>
<p>Se observa una relación lineal negativa entre la salinidad y la riqueza a valores de salinidad bajos entre 33,2 - 33,5 UPS aproximadamente. Mientras que a valores medios y altos de salinidad, se observa una tendencia inversa dada por el término cuadrático. Sin embargo, los valores de riqueza no llegan a recomponerse quedando riquezas bajas en altas salinidades.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>pred_salinidad <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(<span class="fu">update</span>(m_SSS2,<span class="at">correlation =</span> <span class="cn">NULL</span>), <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"SSS [all]"</span>))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred_salinidad )<span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">""</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"SSS [UPS]"</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Relación esperada entre la riqueza (número de taxones) y el polinomio de grado 2 de la salinidad (UPS). Se muestra la relación con su banda de confianza (95%), representada con las regiones sombreadas.</figcaption>
</figure>
</div>
</div>
</div>
<p>Se observa una relación lineal negativa entre gamma y riqueza, donde por cada aumento unitario de tamaño de las partículas, la riqueza disminuye en promedio entre 4.509 y 8.987 numero de taxones, con un 95% de confianza.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pred_gamma <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(<span class="fu">update</span>(m_gamma,<span class="at">correlation =</span> <span class="cn">NULL</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred_gamma )<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">""</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"gamma"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Tp_entregar_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Relación esperada entre la riqueza (número de taxones) y el tamaño de partículas inverso. Se muestra la recta estimada con su banda de confianza (95%), representada con las regiones sombreadas.</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="discusión-y-conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="discusión-y-conclusiones">Discusión y conclusiones</h2>
<div class="justify">
<p>Se observó que existe una relación, tanto entre la salinidad como con el tamaño de los organismos, con la riqueza de plancton de la misma.</p>
<p>Por un lado, se notó que el número de especies varía según el polinomio cuadrado de la salinidad (UPS) (p&lt;0.05), con un mínimo en 33.61 UPS y presentando el máximo de número de taxones en aguas poco salobres, relacionadas con aguas internas de la plataforma.</p>
<p>Además, la cantidad de taxones disminuyó linealmente a menores tamaños de organismos, cayendo en promedio 6.748 números de taxones por unidad de gamma.&nbsp;</p>
<p>De esta manera, se puede concluir que las comunidades presentes en las aguas internas de la plataforma continental poseerán una mayor riqueza, asociada a una menor salinidad y organismos más grandes; frente a las comunidades del talud, las cuales poseerán un menor número de taxones.&nbsp;</p>
</div>
</section>
<section id="biblografia" class="level2">
<h2 class="anchored" data-anchor-id="biblografia">Biblografia</h2>
<p>Falkowski, P. G., Fenchel, T., &amp; Delong, E. F. (2008). The microbial engines that drive Earth’s biogeochemical cycles. Science, 320(5879), 1034-1039.</p>
<p>Ferronato, C., Guinder, V. A., Rivarossa, M., Saraceno, M., Ibarbalz, F., Tillmann, U., … &amp; Flombaum, P. (2025). Insights into protistan plankton blooms in the highly dynamic Patagonian Shelf and adjacent ocean basin in the southwestern Atlantic. Journal of Geophysical Research: Oceans, 130(3), e2024JC021412.</p>
<p>Guinder, V. A., Ferronato, C., Dogliotti, A. I., Segura, V., &amp; Lutz, V. (2024). The phytoplankton of the Patagonian Shelf-break Front. The Patagonian Shelfbreak Front: Ecology, Fisheries, Wildlife Conservation, 49-72.</p>
<p>Kraberg, A., Baumann, M., &amp; Dürselen, C. D. (2010). Coastal phytoplankton: photo guide for Northern European seas. Pfeil.</p>
<p>Lévy, M., Jahn, O., Dutkiewicz, S., Follows, M. J., &amp; d’Ovidio, F. (2015). The dynamical landscape of marine phytoplankton diversity. Journal of the Royal Society Interface, 12(111), 20150481.</p>
<p>Piola, A. R., Palma, E. D., Bianchi, A. A., Castro, B. M., Dottori, M., Guerrero, R. A., … &amp; Saraceno, M. (2018). Physical oceanography of the SW Atlantic Shelf: a review. Plankton ecology of the Southwestern Atlantic: from the subtropical to the subantarctic realm, 37-56.</p>
<p>Rivas, A. L., Dogliotti, A. I., &amp; Gagliardini, D. A. (2006). Seasonal variability in satellite-measured surface chlorophyll in the Patagonian Shelf. Continental Shelf Research, 26(6), 703-720.</p>
<p>Romero, S. I., Piola, A. R., Charo, M., &amp; Garcia, C. A. E. (2006). Chlorophyll‐a variability off Patagonia based on SeaWiFS data. Journal of Geophysical Research: Oceans, 111(C5).</p>
<p><img src="images/dharma.jpeg" class="img-fluid"></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>